[package]
name = "git-remote-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
forge = ["dep:reqwest"]

[dependencies]
base64.workspace = true
claw-core = { path = "../claw-core" }
fs2 = "0.4"
regex.workspace = true
reqwest = { workspace = true, features = ["blocking"], optional = true }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
url.workspace = true
uuid.workspace = true
wait-timeout.workspace = true
