schema_version = 1

# Change these values to rebrand the product without editing source code.
display_name = "RustClaw"
release_artifact_id = "rustclaw"
release_repository = "MatrixCoreX/RustClaw"
small_screen_splash_image = "app-splash-480x320.png"

terminal_banner = '''
######################################################################################
                    __!---===[[[  @@@@  ]]]===---!__
           _!@#￥%……&*()_/      <<<<>>>>      \_!@#￥%……&*()_
        _!@#￥%……&*()_/      <<<<  @@  >>>>      \_!@#￥%……&*()_
      !@#￥%……&*()_+       <<<<  @@@@@@  >>>>       +_)(*&……%￥#@!
      !@#￥%……&*()_+=======<<<<==@@@==@@@==>>>>=======+_)(*&……%￥#@!
      !@#￥%……&*()_+       >>>>  @@@@@@  <<<<       +_)(*&……%￥#@!
        !_)(*&……%￥#@!\      >>>>  @@  <<<<      /!@#￥%……&*()_
           !@#￥%……&*()_\      >>>><<<<      /_)(*&……%￥#@!
                     --===!!![[[  @@@@  ]]]!!!===--

########   ##    ##   #######   ########      #######   ##         ######    ##      ##
##    ##   ##    ##   ##           ##         ##        ##        ##    ##   ##  ##  ##
########   ##    ##   #######      ##         ##        ##        ########   ##  ##  ##
##   ##    ##    ##        ##      ##         ##        ##        ##    ##   ##  ##  ##
##    ##    ######    #######      ##         #######   ########  ##    ##    ###  ###

########################################################################################
'''
