STRINGS = {
    "CN": {
        "app_title": "RustClaw 小屏",
        "switch": "切换",
        "settings": "设置",
        "version": "版本",
        "uptime": "运行时长",
        "queue": "队列",
        "running": "执行中",
        "worker": "Worker",
        "worker_offline": "未运行",
        "memory_rss": "内存 RSS",
        "adapters": "通信端",
        "adapters_memory": "通信端内存",
        "adapters_memory_space": "  通信端内存 ",
        "foot_prefix": "同源请求 /v1/health",
        "update_fmt": "更新: {time} (每{sec}s)",
        "skills_title": "SKILLS",
        "skills_load_fail": "无法加载技能配置",
        "users_title": "用户",
        "users_count": "启用用户",
        "bound_channels": "已绑定通信端",
        "clawd_summary": "Logs",
        "clawd_summary_empty": "暂无摘要",
        "logs_title": "Logs",
        "recent_messages_title": "最近消息",
        "recent_messages_empty": "暂无用户消息",
        "recent_message_more_hint": "在通信端查看",
        "msg_replied_label": "已回复",
        "msg_replied_hint": "已回复，在通信端查看",
        "logs_empty": "暂无日志",
        "settings_title": "设置",
        "language": "语言",
        "lang_en": "EN",
        "lang_cn": "CN",
        "ok": "确定",
        "cancel": "取消",
        "back": "返回",
        "crypto_refresh_hint": "每{sec}秒自动刷新",
        "crypto_empty": "请在 small_screen_markets.toml 配置展示币种",
        "stock_refresh_hint": "每{sec}秒自动刷新",
        "stock_empty": "请在 small_screen_markets.toml 配置展示股票",
        "us_stock_refresh_hint": "每{sec}秒自动刷新",
        "us_stock_empty": "请在 small_screen_markets.toml 配置展示美股",
        "refresh": "刷新",
        "llm_title": "NNI分布式模型 (test)",
        "llm_join": "加入",
        "llm_stop": "停止",
        "llm_pubkey_slot0": "slot 0",
        "llm_pubkey_loading": "正在读取 slot 0.....",
        "llm_pubkey_empty": "还未读取 slot 0",
        "llm_pubkey_error": "获取不到公钥",
        "llm_signing": "正在签名.....",
        "llm_sign_failed": "签名失败",
        "llm_sign_timestamp": "时间",
        "llm_sign_signature": "签名",
        "theme": "界面",
        "theme_default": "默认",
        "theme_matrix": "Matrix",
        "page_visibility": "页面显示",
        "settings_system": "系统",
        "show_messages_page": "消息",
        "show_logs_page": "日志",
        "show_nni_page": "NNI",
        "show_skills_page": "技能",
        "show_weather_page": "天气",
        "show_stock_page": "A股",
        "show_us_stock_page": "美股",
        "show_crypto_page": "加密货币",
        "overview_title": "总览",
        "overview_loading": "加载中.....",
        "overview_tap_hint": "点按展开",
        "overview_skills_enabled": "已启用 {enabled}/{total}",
        "overview_visible_pages": "已显示 {count} 页",
        "overview_configured_count": "已配置 {count} 项",
        "overview_gallery_running": "运行中",
        "overview_gallery_idle": "未运行",
        "weather_title": "天气",
        "weather_loading": "正在获取天气.....",
        "weather_refresh_hint": "启动时和每15分钟自动刷新",
        "weather_updated": "更新",
        "weather_source": "来源",
        "weather_feels_like": "体感",
        "weather_high_low": "最高 / 最低",
        "weather_humidity": "湿度",
        "weather_wind": "风",
        "weather_rain": "降雨",
        "weather_sunrise": "日出",
        "weather_sunset": "日落",
        "weather_error": "天气获取失败: {error}",
        "restart": "重启RustClaw核心",
        "restarting": "重启中.....",
        "wifi_title": "WiFi",
        "wifi_refresh": "刷新列表",
        "wifi_refreshing": "扫描中.....",
        "wifi_connect": "连接 WiFi",
        "wifi_connecting": "连接中.....",
        "wifi_join": "加入",
        "wifi_disconnect": "断开",
        "wifi_disconnecting": "断开中.....",
        "wifi_selected": "已选网络",
        "wifi_password": "密码",
        "wifi_edit_password": "输入密码",
        "wifi_keyboard_done": "完成",
        "wifi_show_password": "显示",
        "wifi_hide_password": "隐藏",
        "wifi_backspace": "退格",
        "wifi_clear": "清空",
        "wifi_space": "空格",
        "wifi_shift": "大小写",
        "wifi_symbols": "符号",
        "wifi_letters": "字母",
        "wifi_prev_page": "上一页",
        "wifi_next_page": "下一页",
        "wifi_no_selection": "请先选择一个 WiFi",
        "wifi_password_required": "该 WiFi 需要密码，请先输入密码。",
        "wifi_empty": "没有扫描到可用 WiFi",
        "wifi_open_hint": "开放网络可直接连接，密码可留空。",
        "wifi_secure_hint": "加密网络请输入密码后连接。",
        "wifi_connected_tag": "已连接",
        "wifi_connect_success": "已连接到 {ssid}",
        "wifi_connect_failed": "连接失败: {error}",
        "wifi_disconnect_success": "已断开 {ssid}",
        "wifi_disconnect_failed": "断开失败: {error}",
        "wifi_scan_failed": "扫描失败: {error}",
        "wifi_scan_hint": "点按列表选择 WiFi，再用屏幕键盘输入密码。",
        "reset_admin_login": "重置管理员账号密码",
        "resetting_admin_login": "重置中.....",
        "reset_admin_login_success": "已重置：admin 账号 rustclaw / rustclaw123456",
        "reset_admin_login_failed": "重置失败: {error}",
        "reset_admin_login_dialog_title": "管理员账号已重置",
        "reset_admin_login_dialog_body": "用户名: rustclaw\n密码: rustclaw123456",
    },
    "EN": {
        "app_title": "RustClaw Small Screen",
        "switch": "Switch",
        "settings": "Settings",
        "version": "Version",
        "uptime": "Uptime",
        "queue": "Queue",
        "running": "Running",
        "worker": "Worker",
        "worker_offline": "Not running",
        "memory_rss": "Memory RSS",
        "adapters": "Adapters",
        "adapters_memory": "Adapters memory",
        "adapters_memory_space": "  Adapters memory ",
        "foot_prefix": "Same-origin /v1/health",
        "update_fmt": "Update: {time} (every {sec}s)",
        "skills_title": "SKILLS",
        "skills_load_fail": "Failed to load skills config",
        "users_title": "Users",
        "users_count": "Enabled users",
        "bound_channels": "Bound channels",
        "clawd_summary": "Logs",
        "clawd_summary_empty": "No summary",
        "logs_title": "Logs",
        "recent_messages_title": "Recent Messages",
        "recent_messages_empty": "No user messages",
        "recent_message_more_hint": "See in Adapters",
        "msg_replied_label": "Replied",
        "msg_replied_hint": "Replied, see in Adapters",
        "logs_empty": "No logs",
        "settings_title": "Settings",
        "language": "Language",
        "lang_en": "EN",
        "lang_cn": "CN",
        "ok": "OK",
        "cancel": "Cancel",
        "back": "Back",
        "crypto_refresh_hint": "Auto refresh every {sec}s",
        "crypto_empty": "Configure crypto items in small_screen_markets.toml",
        "stock_refresh_hint": "Auto refresh every {sec}s",
        "stock_empty": "Configure stock items in small_screen_markets.toml",
        "us_stock_refresh_hint": "Auto refresh every {sec}s",
        "us_stock_empty": "Configure US stocks in small_screen_markets.toml",
        "refresh": "Refresh",
        "llm_title": "Network Native Intelligence (test)",
        "llm_join": "Join",
        "llm_stop": "Stop",
        "llm_pubkey_slot0": "Slot 0",
        "llm_pubkey_loading": "Loading slot 0.....",
        "llm_pubkey_empty": "Slot 0 not loaded yet",
        "llm_pubkey_error": "Public key unavailable",
        "llm_signing": "Signing.....",
        "llm_sign_failed": "Sign failed",
        "llm_sign_timestamp": "Time",
        "llm_sign_signature": "Signature",
        "theme": "Theme",
        "theme_default": "Default",
        "theme_matrix": "Matrix",
        "page_visibility": "Visible Pages",
        "settings_system": "System",
        "show_messages_page": "Messages",
        "show_logs_page": "Logs",
        "show_nni_page": "NNI",
        "show_skills_page": "Skills",
        "show_weather_page": "Weather",
        "show_stock_page": "A Shares",
        "show_us_stock_page": "US Stocks",
        "show_crypto_page": "Crypto",
        "overview_title": "Overview",
        "overview_loading": "Loading.....",
        "overview_tap_hint": "Tap to open",
        "overview_skills_enabled": "Enabled {enabled}/{total}",
        "overview_visible_pages": "{count} pages visible",
        "overview_configured_count": "{count} configured",
        "overview_gallery_running": "Running",
        "overview_gallery_idle": "Idle",
        "weather_title": "Weather",
        "weather_loading": "Loading weather.....",
        "weather_refresh_hint": "Fetch on startup and every 15 minutes",
        "weather_updated": "Updated",
        "weather_source": "Source",
        "weather_feels_like": "Feels like",
        "weather_high_low": "High / Low",
        "weather_humidity": "Humidity",
        "weather_wind": "Wind",
        "weather_rain": "Rain",
        "weather_sunrise": "Sunrise",
        "weather_sunset": "Sunset",
        "weather_error": "Weather fetch failed: {error}",
        "restart": "Restart RustClaw Core",
        "restarting": "Restarting.....",
        "wifi_title": "WiFi",
        "wifi_refresh": "Refresh",
        "wifi_refreshing": "Scanning.....",
        "wifi_connect": "Connect WiFi",
        "wifi_connecting": "Connecting.....",
        "wifi_join": "Join",
        "wifi_disconnect": "Disconnect",
        "wifi_disconnecting": "Disconnecting.....",
        "wifi_selected": "Selected",
        "wifi_password": "Password",
        "wifi_edit_password": "Enter Password",
        "wifi_keyboard_done": "Done",
        "wifi_show_password": "Show",
        "wifi_hide_password": "Hide",
        "wifi_backspace": "Back",
        "wifi_clear": "Clear",
        "wifi_space": "Space",
        "wifi_shift": "Shift",
        "wifi_symbols": "Symbols",
        "wifi_letters": "Letters",
        "wifi_prev_page": "Prev",
        "wifi_next_page": "Next",
        "wifi_no_selection": "Select a WiFi first",
        "wifi_password_required": "This WiFi requires a password. Enter the password first.",
        "wifi_empty": "No WiFi networks found",
        "wifi_open_hint": "Open network: password can be empty.",
        "wifi_secure_hint": "Secure network: enter password first.",
        "wifi_connected_tag": "Connected",
        "wifi_connect_success": "Connected to {ssid}",
        "wifi_connect_failed": "Connect failed: {error}",
        "wifi_disconnect_success": "Disconnected from {ssid}",
        "wifi_disconnect_failed": "Disconnect failed: {error}",
        "wifi_scan_failed": "Scan failed: {error}",
        "wifi_scan_hint": "Tap a WiFi, then use the on-screen keyboard to enter the password.",
        "reset_admin_login": "Reset admin username/password",
        "resetting_admin_login": "Resetting.....",
        "reset_admin_login_success": "Reset done: admin rustclaw / rustclaw123456",
        "reset_admin_login_failed": "Reset failed: {error}",
        "reset_admin_login_dialog_title": "Admin login reset",
        "reset_admin_login_dialog_body": "Username: rustclaw\nPassword: rustclaw123456",
    },
}
